### ISSUE TITLE
Issue with water and SAFT-VR-Mie in pyctp

### ISSUE THREAD

**Issue by gustavochm** [SINTEF/thermopack#11]
Hey!

First of all, I would like to thank you for your work.  I discovered thermopack recently and now I am trying to learn how to use it. I would like to clarify that I am not familiar with developing in Fortran but I am able to understand the logical sequence of your source files. I am using the pycThermopack interface.  By the way, I compiled thermopack in Windows subsystem for Linux (wsl2) (ubuntu).

I am using jupyter notebook to run the examples that you provided and I got some issues when I modify the components in the SAFT-VR-Mie EoS, specifically when using water. The following code makes the kernel to die.

```
# Instanciate and init SAFT-VR Mie object
svrm = saftvrmie.saftvrmie()
svrm.init("H2O")

m, sigma, eps, lambda_a, lambda_r = svrm.get_pure_fluid_param(1)
m, sigma, eps, lambda_a, lambda_r
```
I got the following error at the terminal:

```  saft module: dsysv failed when computing X_T.```

I  checked and you provide parameters for water (4C). I thought that this error might be due to the association contribution, but I don't get the error when setting ethanol (```svrm.init("ETOH")```).

Also, from what I have read about thermopack is that you included several pure fluid and mixture interaction parameters in the source files (.f90). Is there any way to add a custom fluid (user-defined) without modifying the source files? Furthermore, can you optimize pure fluid parameters using thermopack (SAFT-VR-Mie, SAFT-VRQ-Mie or PC-SAFT)? 

Thanks in advance for your time!

Greets,
Gustavo.

**Comment by morteham** [comment]
Hi Gustavo!

Nice to see that you are using thermopack. I will try to help you getting SAFT-VR-Mie to work for H2O.

I reproduced the bug on my computer this morning, but I have to debug in order to see why the critcial point solver run during init is fails. It will take a couple of days before I have the proper time to do this.

Most pure fluid parameters are stored in the `thermopack/fluids/` folder. You can add fluids here (new file), and run the complist.py script in `thermopack/addon/pyUtils/`. It will generate a fortran file (compdatadb.f90) that you can copy to `thermopack/src` and recompile to include the new fluid in thermopack. Unfortunately the saftvrmie parameter database is not included in these files, and new fluid parameters must be coded directly in the fortran code (saftvrmie_parameters.f90). Some mixture parameters are found in `thermopack/binaries`, and code can be generated with the binarylist.py script.

Regarding the parameter optimization we usually do this through the python inteface. There is no code available (open source) to do this, but if you set up an objective function and find a suitable optimizer, you can set the pure fluid parameters trough the python interface. For SAFT-VR-Mie and SAFT-VRQ-Mie you use the `set_pure_fluid_param` to modify the pure fluid parameters. For PC-SAFT the pure fluid parameters are not yet added to the python inteface. I will add it to the TODO list.

Regards,
Morten

**Comment by gustavochm** [comment]
Dear Morten,

Thanks for your quick response! I have continued running some calculations with thermopack and it is amazing how well it performs! Amazing job!

By the way, I found something that might be related to the association bug with water when using SAFT-VR-Mie EoS. I computed the phase diagram at 320K of Hexane (1) and Ethanol (2), I got no issues when configuring the mixture but for me the results are a little off. This is the plot that I got:

![SAFT-VR-Mie](https://user-images.githubusercontent.com/42041445/114704143-421bbf00-9cf4-11eb-8fc8-ad4a19cfc3c7.jpg)

I knew before hand that this mixture has an azeotrope (I compared the results with some calculations of my own, SGTPy). It is seems there is a bug for the association contribution with SAFT-VR-Mie, I say this because I got the same results when comparing calculations for mixtures of non-associating fluid e.g. Hexane and Octane.

Additionally, I computed the same diagram using PC-SAFT. The results seems fine to me.

![PCSAFT](https://user-images.githubusercontent.com/42041445/114704139-3e883800-9cf4-11eb-89b7-5fb2de946d88.jpg)

Hope this contribute to find the bug

Regards,

Gustavo

**Comment by morteham** [comment]
Dear Gustavo,

Sorry, but it turns out the implementation of the association contribution for the SAFT-VR MIe model is not completed. I will require quite some effort to implement the work ["The A in SAFT" Dufal et al. (2015)](https://doi.org/10.1080/00268976.2015.1029027) to get this up and running. I realize that providing parameters for associating fluids is misleading, and therefore I will comment these code lines.

Regards,
Morten

**Comment by gustavochm** [comment]
Dear Morten,

Thanks for the update!

Greets,
Gustavo
